apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=      # base64 encoded value for 'admin'
  POSTGRES_PASSWORD: LW0gc3Ryb25nUGFzczEyMwo=   # base64 encoded values for 'admin' and '-m strongPass123\n'
